Remove unnecessary password attribute in osgi.bundle
Removes the password attribute `;password=GlassFish` in osgi.bundle, which is unnecessary since the repackaged asm is no longer used.
This fixes `java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor` in jdbc devtests.

Signed-off-by: Takahiro Nagao <nagao.takahiro@fujitsu.com>